package zetashift.cta

enum AST:
  case Number(value: Double)
  case Identifier(value: String)
  case Not(term: AST)
  case Equal(left: AST, right: AST)
  case NotEqual(left: AST, right: AST)
  case Add(left: AST, right: AST)
  case Subtract(left: AST, right: AST)
  case Multiply(left: AST, right: AST)
  case Divide(left: AST, right: AST)
  case Call(callee: String, arguments: Vector[AST])
  case Return(term: AST)
  case Block(statements: Vector[AST])
  case If(conditional: AST, consequence: AST, alternative: AST)
  case Function(name: String, parameters: Vector[String], body: AST)
  case Var(name: String, value: AST)
  case Assign(name: String, value: AST)
  case While(conditional: AST, body: AST)
